### ISSUE TITLE
Older songs not displaying whether or not open notes appear

### ISSUE THREAD

**Issue by ataeaf** [Paturages/chorus#189]
Older songs not displaying whether or not open notes appear. This does not affect newer songs w/ open notes, for the record.

**Comment by Paturages** [comment]
Yup, I messed up something in the scanning process that I have since fixed in the code, but fixing the rest of the songs would require a full scan which last time I did it took about 3 days for some reason... so I'm holding off on fixing them until I roll the next batch of updates, which will be soon (hopefully).

**Comment by Paturages** [comment]
Full scan has been rolled out.
