### ISSUE TITLE
Over 600 vulnerabilities?

### ISSUE THREAD

**Issue by rogersachan** [Paturages/chorus#216]
![image](https://user-images.githubusercontent.com/7173984/46750710-8858b900-cc86-11e8-9673-787e35879c99.png)

Is there an issue preventing the upgrade of certain packages in use?

**Comment by Paturages** [comment]
I deleted the `package-lock.json` file and re-installed from scratch and seemed to get this result:
![image](https://user-images.githubusercontent.com/9801350/46752488-a1309100-ccbd-11e8-928d-a93e27647175.png)

Mostly my own free time is preventing me from working on the code itself though, but I know there's room for upgrading (e.g. most notably `babel-core` to `@babel/core` and friends, replace `postcss-cssnext`, most likely just use `webpack-dev-server` instead of `webpack` + `browser-sync`... and just bump the rest up to latest stable).

I'm currently (slowly) working on refactoring/restructuring for a "v2", so I'll most likely have fresh dependencies on that version instead.

**Comment by rogersachan** [comment]
Alright, thanks!
