### ISSUE TITLE
Website Structure

### ISSUE THREAD

**Issue by undergrin** [Paturages/chorus#324]
Hello, I am sorry to write this, but the current layout of the website is really bad. The old layout was much better. In the current one I can't even see the genre of the song which before would allow me to try new bands but that are in a genre I like. Also, you can't even copy and paste the name of the band and song because a black pop up window comes up when you hover your mouse over the name of the song. The current layout prevents me from discovering new bands and songs because its literally just the song name. And if I'm not familiar with that song then I'm just not going to want to download unlike before when I can at least see the genre and easily copy/paste the name into YouTube, it would allow me to discover new songs I might like. The current design is also just plain unattractive to look at. Please change it back or with time and care come up with something better. Although there really wasn't anything wrong with the old one. But with time I suppose there can be a better way to organize and present the songs, but this current layout just is not the answer.

**Comment by Paturages** [comment]
hi, thanks for the feedback and insight, and sorry about the inconveniences, it's always useful to learn and know how people are using this thing

The main thing with the old design is that there was too much information displayed by default, so the reasoning was to hide some of it under mouseovers and feedback for that was generally positive in that regard. However I do think there's room for an amount of incremental changes and tuning.

The latest commit (https://github.com/Paturages/chorus/commit/2421c3588d628d390003e83b464f647c6c1e6885), which should now be live (ctrl+f5 if not), tweaks the following:
* try out another font which seems less rough to me
* unhide "song metadata": album, genre, song length
* move modified time and checksum to the right because there's space left
* fix some minor alignment issues

this should at the very least alleviate the song metadata copy/paste issue, lemme know what you think

**Comment by undergrin** [comment]
Hey I appreciate the response. The issues I was having are fixed! This is definitely better and I want to thank you.
