### ISSUE TITLE
Some direct download archives contain ch.dat's or files begin with a backslash

### ISSUE THREAD

**Issue by justync7** [Paturages/chorus#74]
So, recently I wrote a small fishell script to download songs from chorus, which you can find ![here](https://github.com/justync7/dotfiles/blob/master/scripts/chget.fish).

In doing this I noticed some minor problems. Most notably, the downloads are absolutely massive. 50MB~ for a single song isn't abnormal from what I've seen. (Is this normal?) I suspect this is something to do with the ch.dat's that are contained in the download possibly.

Additionally, I noticed that some songs (mostly ones in offical games) have all their files prefixed by a leading backslash. (Possibly a Windows vs Linux issue? Not sure.) This causes the song to be bad until manually renaming every file to remove the backslash.

I also noticed that rather than GDrive links like most songs, the official games are hosted on chorus directly. Did you zip them from your local copy? That'd explain the ch.dat's being included.

**Comment by Paturages** [comment]
I see you noticed the `directLinks`, that's really cool! Lemme know if there are any issues with them because I haven't actually thoroughly tested them yet.

`ch.dat` are remnants of the way old versions of Clone Hero handled song caching. They're small enough though (<2KB) so forgetting to remove them when packaging doesn't make much of an impact. What makes the bulk of some song download sizes though is **stems** and **video backgrounds**. Stems usually include multiple audio files, one for each instrument, which indeed sums up to an average of 50 MB per song. Video background sizes depend on encoding: I've seen people provide 500 MB archives, but it should average maybe 100-150 MB. There is, however, a hard upper limit of 200 MB I set for Google Drive archives ([see here](https://github.com/Paturages/chorus/blob/master/src/drivers/google-drive.js#L76)).

As for the songs with a leading backslash, it was most definitely a blunder on my end when I zipped some of these files. Do you happen to have a list of them? I thought I fixed them all.

**Comment by justync7** [comment]
I'm not sure what specifically, but I've mostly noticed it with GH{1,2,3} songs.

**Comment by Paturages** [comment]
GH2 and GH:WoR fixed, I checked them all... finally! Apologies for the delay lol.
